### ISSUE TITLE
0.63.7版本报错，求大佬更新

### ISSUE THREAD

**Issue by daomengRen** [SiriusXT/trilium-left-panel-auto-zoom#4]
谢谢大佬！！！

**Comment by Nriver** [comment]
我这里没有问题，具体什么报错你要贴出来

**Comment by daomengRen** [comment]
报错如下: 
```04:20:12.382 JS Error: 未捕获的错误: 信息: Uncaught TypeError: Cannot read properties of undefined (reading 'style'), URL: , 行数: 24, 列数: 18, 错误对象: {}, 堆栈: TypeError: Cannot read properties of undefined (reading 'style')
    at showR (eval at <anonymous> (https://xxx/assets/v0.63.7/app-dist/desktop.js:2:51095), <anonymous>:24:18)
Stack: Error
    at Object.k [as logError] (https://xxx/assets/v0.63.7/app-dist/desktop.js:2:118317)
    at Si.window.onerror (https://xxx/assets/v0.63.7/app-dist/desktop.js:2:639310)```

看不出是哪里出问题了，但是关闭这个插件的话，这个报错就消失了，是不是和其他的冲突了，求大佬解答

**Comment by daomengRen** [comment]
与上面问题无关，故关闭
